spring:
  r2dbc:
    database: ouruserdb
    url: r2dbc:postgresql://0.0.0.0:5432/${spring.r2dbc.database}
    username: root
    password: rootroot

  application:
    name: users-service

  config:
    import: optional:configserver:http://localhost:8888

#disable service discovery for local profile to not try & reach repository
  cloud:
    discovery:
      enabled: false

server:
  port: ${PORT:0}    # if port 0 - random port assigned
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


jwt:
  secretKey: SuperLongAndVerySecureKey-[].~^+$&4
  refreshTokenExpirationAfterMilliseconds: 86400000
  accessTokenExpirationAfterMilliseconds: 420000